org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11

mod_version=0.3.0
maven_group=net.justacoder.shadowclient
archives_base_name=shadowclient

fabric_version=0.92.0+1.20.1