org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mod properties
mod.version=0.3
mod.group=net.justacoder.shadowclient
mod.id=shadowclient
mod.name=ShadowClient

# Global dependencies
deps.fabric_loader=0.18.4
